# Generated by Django 4.1 on 2022-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ocupacao',
            field=models.CharField(choices=[('0', 'aluno'), ('1', 'professor')], default=0, max_length=11),
            preserve_default=False,
        ),
    ]
