# Generated by Django 4.1 on 2022-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('pergunta', models.TextField()),
                ('alternativa1', models.CharField(max_length=260)),
                ('alternativa2', models.CharField(max_length=160)),
                ('alternativa3', models.CharField(blank=True, max_length=160, null=True)),
                ('alternativa4', models.CharField(blank=True, max_length=160, null=True)),
                ('certa', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('senha2', models.CharField(max_length=30)),
            ],
        ),
    ]
