# Generated by Django 4.1 on 2022-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=2)),
            ],
        ),
    ]
