# Generated by Django 4.1 on 2022-10-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_respota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respota',
            new_name='Resposta',
        ),
    ]
