# Generated by Django 4.1 on 2022-10-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_respota_resposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa1',
            new_name='alternativaa',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa2',
            new_name='alternativab',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa3',
            new_name='alternativac',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa4',
            new_name='alternativad',
        ),
    ]
