# Generated by Django 4.1 on 2022-10-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_alternativa1_questao_alternativaa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='questao',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.questao'),
            preserve_default=False,
        ),
    ]
