# Generated by Django 4.1 on 2022-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resposta_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='questao',
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(max_length=1),
        ),
    ]
