# Generated by Django 4.1 on 2022-10-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_resposta_questao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='questao',
        ),
    ]
