# Generated by Django 4.1 on 2022-11-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_resposta_questao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
